### ISSUE TITLE
Rule Numbering

### ISSUE THREAD

**Issue by Smada-nailuj** [Strevia/phants-nomic#10]
I haven't seen any rules about when you can propose a rule change, so how do you number your rule proposal if there are multiple pending rules?

**Comment by Strevia** [comment]
The readme has this clause:

> conflicting pull requests

> Sometimes two pull requests may both be modifying the same part of the rules. If one is merged in before the other, the outstanding pull request may become conflicted. Github will display a grey message on the pull request indicating this. The proposer will have to close the conflicted pull request, create a new one that is not conflicting, and begin the voting process again.

Personally I interpret that as: both will assume they will be merged first, and once one has been merged the other will need to be updated.

**Comment by Smada-nailuj** [comment]
ok that makes sense
