### ISSUE TITLE
creation of new files

### ISSUE THREAD

**Issue by Strevia** [Strevia/phants-nomic#26]
The recently proposed #25 creates a new file appendex_F.md. The creation of new files is not currently defined in any way in the rules. Therefore, as the sole moderator and owner of the GitHub repository, it is implicitly my responsibility for how this happens.

However, I do not want this to be my sole responsibility, for a few reasons:
- It is against the spirit of the game
- I may make a decision someone disagrees with, which may lead to a long arbitration process
- This could lead to a slippery slope

Therefore, before we go creating new files, I think we need to define how new files can be created, and which files need to be approved. My suggestion would be to move the rules into its own subfolder, and change rule 1 to specify the entire subfolder is what can be changed. For the reasons listed above, I am making this issue to see if anyone has any other suggestions or disagrees with this.

**Comment by Smada-nailuj** [comment]
I am not against the creation of a rule folder, would this be an administrative action or a player action though?

**Comment by Strevia** [comment]
I think since it's editing rules.md it needs to be a player action
