### ISSUE TITLE
log base 2 of zero is negative infinity 

### ISSUE THREAD

**Issue by Strevia** [Strevia/phants-nomic#32]
Ok can we just agree not to give negative infinity points if you don't have a tower

**Comment by Smada-nailuj** [comment]
Yes

**Comment by Smada-nailuj** [comment]
Also technically it's only the LIMIT of log base 2 of zero is negative infinity.

**Comment by Strevia** [comment]
I was assuming we're using floating point arithmetic not abstract math arithmetic, since this all takes place on a computer
