### ISSUE TITLE
Build two blocks, add them to my tower

### ISSUE THREAD

**Issue by Strevia** [Strevia/phants-nomic#35]
### Name of action I am taking
Build two blocks, add them to my tower

### Rule which allows me to take this action
Rule 5 (building) and rule 9 (placing)

### Expected outcome of this action
This should cost me 3 points: 2 for building the blocks, 0 for placing the first block, and 1 for placing the second block.

### Other notes (if something is common enough I may add it to the template)
As this is the first time a tower is being built, I will not perform my moderator duties until I get an OK from @Smada-nailuj

**Comment by Smada-nailuj** [comment]
Yep that seems to check out as correct
