### ISSUE TITLE
Should #40 get points?

### ISSUE THREAD

**Issue by Smada-nailuj** [Strevia/phants-nomic#41]
recently a player has created a pull request to an active pull request instead of the main branch. specifically #40.

Should that pull request be accepted would that player get any points, and if so when would they get those points?

is it against the rules to propose multiple rules in one pull request? 

there are probably more implications and questions about this situation then covered here,

**Comment by Strevia** [comment]
After consideration, I think pull requests on top of pull requests creates more issues than it solves. It begs the question of how many points they would get, and it could create a tangled web of pull requests on pull requests.
It is my opinion that any content on a non-main branch is solely owned by the owner of said non-main branch. Therefore, a pull request into it could be accepted unilateraly and does not gain the player who makes it any points. (I'll let you close #40 if you agree with this stance).

For multiple rules in a pull request, the rules do not state any stance on the matter, so I see no problems with it. They also state you get points for making a proposal and it passing. If multiple changes are made in one proposal, they all pass at the same time.
