### ISSUE TITLE
New SpellChecker

### ISSUE THREAD

**Issue by Strevia** [Strevia/phants-nomic#65]
There is a Spell Checker now!
Doesn't seem like it is working on currently open pull requests, but from testing it will work on new pull requests.
A couple typos seem to have made it into our rules (5).
Also, we can add words to [this file](https://github.com/Strevia/phants-nomic/blob/master/.github/actions/spelling/expect.txt) if they aren't in the dictionary (like kilocubit).

**Comment by Smada-nailuj** [comment]
How does it work?

**Comment by Smada-nailuj** [comment]
What five typos made it in to the rules?
