### ISSUE TITLE
A Lot Of Stuff

### ISSUE THREAD

**Issue by Strevia** [Strevia/phants-nomic#92]
### Name of action I am taking
Build 1 block, add it to my tower, build 2 apartments, build town hall

### Rule which allows me to take this action
Rule 5 (building blocks), rule 9 (adding them), rule 10 (apartments and town hall)

### Expected outcome of this action
Height of my tower should be 3, with two apartments and a town hall. Point cost:
1 for block
2 to add to tower
2 + 4 for apartments
1 for town hall
10 points

**Comment by Strevia** [comment]
@Smada95 numbers check out?

**Comment by Smada95** [comment]
Yes

**Comment by Smada95** [comment]
It's called a Tower Hall Though
